Remove git-sweep to unblock Homebrew bundle installation
git-sweep from julienandreu/tap is causing brew bundle to fail:
  Error: No available formula with the name "git-sweep"

This blocks ALL Homebrew casks from installing (Docker, Cursor, etc.)

Removing for now. Can be installed manually later with:
  brew install git-sweep (if tap is set up)
Or download from: https://github.com/julienandreu/git-sweep/releases